> ### **Assignment 2 - Numpy Array Operations** 
>


Write a short introduction about Numpy and list the chosen functions. 

function1 = np.append 

function2 = np.average

function3 = np.arange

function4 = np.squeeze

function5 = np.vstack




In [33]:
import numpy as np

## Function 1 - np.append
np.append function add elements to the end of an array provided that the dimensions of the elements should be same.

In [34]:
# Example 1 - working (change this)
arr1 = [1, 2, 1, 25, 26]
np.append(arr1, [24, 23, 15])


array([ 1,  2,  1, 25, 26, 24, 23, 15])

We can put lists as an element inside the array, then append it with the expected lists or any element regardless of their size.



In [35]:
# Example 2 - working
arr2 = [[2, 4, 5], [6, 7, 8]]
np.append(arr2, [10, 12])
np.append(arr2, [10, 12, 13, 14])

array([ 2,  4,  5,  6,  7,  8, 10, 12, 13, 14])

When axis is specified, arrays must have the same shape.

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [[14, 15, 16]], axis = 0)

array([[ 2,  4,  5],
       [ 6,  7,  8],
       [14, 15, 16]])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Some closing comments about when to use this function.

In [37]:
# Fix
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [[14, 15, 16], [12, 15, 16]], axis = 0)

array([[ 2,  4,  5],
       [ 6,  7,  8],
       [14, 15, 16],
       [12, 15, 16]])

In arr3, index 0 has 2 dimensions, while the element to be appended has 1 dimension, thus breaks down. To fix this, the element to be appended should have 2 dimensions as well.

## Function 2 - average()

Add some explanations

In [38]:
#average() function is to calculate mean values across dimensions in an array. 
# It will return the average of a numpy array of all values along the given axis

In [39]:
# Example 1 - working
arr10 = [[5,2,6], [8,5,1], [3,6,1]]
np.average(arr10)

4.111111111111111

Explanation about example

In [40]:
# Example 2 - working
arr13 = [15,10,25,20,5]
np.average(arr13)

15.0

Explanation about example

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
sample = [-21,12,9,4]
np.average(sample,[5,3,6,14], axis=0)

TypeError: _average_dispatcher() got multiple values for argument 'axis'

Explanation about example (why it breaks and how to fix it)

In [42]:
sample = [-1,12,24,22]
np.average(sample)

14.25

Some closing comments about when to use this function.

## Function 3 - np.arange

Add some explanations

In [46]:
# Example 1 - working
np.arange(5,10)

array([5, 6, 7, 8, 9])

Explanation about example

In [48]:
# Example 2 - working
np.arange(5,15,3)

array([ 5,  8, 11, 14])

Explanation about example

In [49]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange(5,15,str)

TypeError: unsupported operand type(s) for /: 'int' and 'type'

Explanation about example (why it breaks and how to fix it)

In [51]:
np.arange(5,15,3,int)

array([ 5,  8, 11, 14])

Some closing comments about when to use this function.

## Function 4 - np.squeeze

Add some explanations

In [58]:
# Example 1 - working
sam_squeeze = np.array([[[3,1],[4,2],[5,3],[6,4],[7,5],[8,6]]])
sam_squeeze.shape

(1, 6, 2)

In [59]:
np.squeeze(sam_squeeze, axis=0).shape

(6, 2)

Explanation about example

In [60]:
# Example 2 - working
example_squeeze = np.array([[[0,0], [1,1], [2,2]]])
example_squeeze

array([[[0, 0],
        [1, 1],
        [2, 2]]])

In [61]:
np.squeeze(example_squeeze,axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

Explanation about example

In [62]:
# Example 3 - breaking (to illustrate when it breaks)
example_squeeze = np.array([[[0,0], [1,1], [2,2]]])
example_squeeze.shape

(1, 3, 2)

In [63]:
np.squeeze(example_squeeze).shape

(3, 2)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 5 - np.vstack

Add some explanations

In [64]:
# Example 1 - working
arr4 = np.array([65, 32, 87])
arr5 = np.array([34, 95, 91])
np.vstack((arr4,arr5))

array([[65, 32, 87],
       [34, 95, 91]])

Explanation about example

In [65]:
# Example 2 - working
arr4 = np.array([[65], [32], [87]])
arr5 = np.array([[34], [95], [91]])
np.vstack((arr4,arr5))

array([[65],
       [32],
       [87],
       [34],
       [95],
       [91]])

Explanation about example

In [69]:
# Example 3 - breaking (to illustrate when it breaks)
example_vstack1 = np.array([[3.1], [50], [7.2]])
example_vstack2 = np.array([5.8], [7], [9.0])
np.vstack((example_vstack1,example_vstack2))

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

Explanation about example (why it breaks and how to fix it)

In [72]:
example_vstack1 = np.array([[3.1], [50], [7.2]])
example_vstack2 = np.array([[5.8], [7], [9.0]])
np.vstack((example_vstack1,example_vstack2))

array([[ 3.1],
       [50. ],
       [ 7.2],
       [ 5.8],
       [ 7. ],
       [ 9. ]])

Some closing comments about when to use this function.